
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Build environment variables
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Production context: all deploys from the main branch will use these settings
[context.production]
  command = "npm run build"
  publish = "dist"

# Deploy previews from pull requests
[context.deploy-preview]
  command = "npm run build"
  publish = "dist"

# Branch deploys
[context.branch-deploy]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# This redirect rule ensures that all routes are handled by the single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better caching and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
