// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://coflowvqtsacmwxhqwpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvZmxvd3ZxdHNhY213eGhxd3B2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTA2NjgsImV4cCI6MjA2MzI4NjY2OH0.7Xa6ENEY-FOU3dg937PFFatzUbNo5YfPvfwAs-hyvaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);